name: Test Git Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Vérifier la version de Git
        run: git --version

      - name: Afficher les fichiers du projet
        run: ls -la

      - name: First interaction
        uses: actions/first-interaction@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Bonjour ! Merci d’avoir ouvert votre première *issue* dans ce dépôt. Nous allons la traiter dès que possible.
          pr-message: |
            Merci pour votre première *pull request* ! Un membre de l’équipe va la réviser sous peu.
